apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  namespace: default
spec:
  replicas: 3
  selector: 
    matchLabels:
      demo: web
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        demo: web
    spec:
      containers:
        - name: docker-demo
          image: kaloyanpr/docker-demo:2.0
---
apiVersion: v1
kind: Service
metadata:
  name: docker-demo-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    demo: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001